version: "3.8"

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: afneto
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: authentication-api_mongo_1
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_URL: mongodb://localhost:27017 
    ports:
      - "27017:27017"
    volumes:
      - ${HOME}/.volumes/authentication/MongoDB/data:/data/db
    networks:
      - mongo-compose-network
  redis: 
    image: redis
    command: redis-server --requirepass root --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      -  ${HOME}/.volumes/authentication/Redis/data:/var/lib/postgresql/data

  app:
    image: afonsobsneto/authentication-api
    environment:
      MONGO_URL: mongodb://root:root@authentication-api_mongo_1/users?authSource=admin
      PORT: ${PORT}
    ports:
      - "3333:${PORT}"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge